# Generated by Django 4.2 on 2025-05-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('세종', '세종'), ('충남', '충남'), ('경북', '경북'), ('울산', '울산'), ('경남', '경남'), ('부산', '부산')], max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
